checks:
    php:
        code_rating: true
        duplication: true

before_commands:
    - "composer install --prefer-dist"

tools:
    php_mess_detector: true
    php_analyzer: true
    php_code_coverage: true
    php_pdepend: true
